export interface ISpriteItem {
  id: string;
  type: SpriteItemType;
  posX: number;
  posY: number;
  rotation?: number;
}

export enum SpriteItemType {
  unknown = "unknown",
  grass1 = "grass1",
  grass2 = "grass2",
  grass3 = "grass3",
  grass4 = "grass4",
  grass5 = "grass5",
  grassLong1 = "grassLong1",
  grassLong2 = "grassLong2",
  grassLong3 = "grassLong3",
  grassShroom1 = "grassShroom1",
  grassShroom2 = "grassShroom2",
  grassShroom3 = "grassShroom3",
  treeLarge1 = "treeLarge1",
  treeLarge2 = "treeLarge2",
  treeLarge3 = "treeLarge3",
  treeLarge4 = "treeLarge4",
  treeLarge5 = "treeLarge5",
  treeLarge6 = "treeLarge6",
  treeLarge7 = "treeLarge7",
  treeLarge8 = "treeLarge8",
  treeTall1 = "treeTall1",
  treeTall2 = "treeTall2",
  treeTall3 = "treeTall3",
  treeTall4 = "treeTall4",
  treeTall5 = "treeTall5",
  treeTall6 = "treeTall6",
  tree1 = "tree1",
  tree2 = "tree2",
  tree3 = "tree3",
  tree4 = "tree4",
  leaves1 = "leaves1",
  leaves2 = "leaves2",
  leaves3 = "leaves3",
  bush1 = "bush1",
  bush2 = "bush2",
  path1Innertl = "path1Innertl",
  path1Innertc = "path1Innertc",
  path1Innertr = "path1Innertr",
  path1Innercl = "path1Innercl",
  path1Innercc = "path1Innercc",
  path1Innercr = "path1Innercr",
  path1Innerbl = "path1Innerbl",
  path1Innerbc = "path1Innerbc",
  path1Innerbr = "path1Innerbr",
  pathOuter1tl = "pathOuter1tl",
  pathOuter1tr = "pathOuter1tr",
  pathOuter1bl = "pathOuter1bl",
  pathOuter1br = "pathOuter1br",
  path1Full = "path1Full",
  path1FullInner = "path1FullInner",
}
